### ISSUE TITLE
Concurrent accesses to memcached can race

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-customs-server#103]
The logic for maintaining our records in memcached currently goes like this:

* get the record from memcached
* inspect it, update it with new data, etc
* unconditionally write it back to memcached

This leaves the potential for concurrent accesses to race each other and overwrite changes made from another processes.  We should change it to use compare-and-set when writing the data back so that we don't lose anything.

**Comment by vbudhram** [comment]
@rfk from mtg, priority?

**Comment by rfk** [comment]
We're going to try to move away from memcached for this service, so I'm closing memcached-related bugs in the backlog
