### ISSUE TITLE
Emit more metrics about what we're blocking and why

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-customs-server#106]
This is necessary to help tell if the blocking is working, and to help diagnose failures if it's triggering false positives.  As a start, we should emit events whenever:
- rate-limiting is applied to a particular item
- an explicit ban is placed on an ip
- an account is locked

**Comment by shane-tomlinson** [comment]
@rfk - we are putting this in next, can you re-prioritize if you feel the need?

**Comment by philbooth** [comment]
@rfk, we raised this in triage, does it still need doing or can we close this out?

**Comment by rfk** [comment]
Let's close this out, I don't think we can do a good job of it on top of the current infra
