### ISSUE TITLE
Don't count errno 121 as a failed login attempt

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-customs-server#111]
Errno 121 is `ACCOUNT_LOCKED`, and it's the error code that auth-server returns whenever you're trying to log in to a locked account.  The content-server's logic for handling locked accounts, involved *polling* by trying the login over and over again until it stops returning this errno.  So as it stands, this polling will count as a bunch of failed login attempts on the account.

It seems reasonable to me, that we wouldn't count this error towards your failed-logins total, because the account has already been locked out.

**Comment by rfk** [comment]
Alternately: provide a non-login endpoint at which content-server can poll for account locked status

**Comment by shane-tomlinson** [comment]
> Alternately: provide a non-login endpoint at which content-server can poll for account locked status

I'm partial to this, though I haven't thought through the repercussions.

**Comment by seanmonstar** [comment]
I've looked all throughout the customs server, and there's nothing regarding that errno. I also do not see any specific instance of `customs.flag` that includes the `ACCOUNT_LOCKED` errno in the auth-server.

**Comment by rfk** [comment]
On balance, I think we should close this and fix it in the customs-server instead, by doing something other than poll the login endpoint for status.  Closing in favour of https://github.com/mozilla/fxa-content-server/issues/3740
