### ISSUE TITLE
accountLogin will soon be an email-sending event

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-customs-server#116]
When sign-in confirmation goes live, /account/login will send an email.  Should we add "accountLogin" to the list of email-sending events here, or is it different enough from the others that we don't need to worry about it?  (For example, it's different in that you have to have an active login session, whereas other email-sending endpoints are unauthenticated).

**Comment by vbudhram** [comment]
My initial impression is that this should not count against a user's email quota. Not sure if this is 100% applicable, but `/password/change/finish` can send an unlimited amount of emails if a user constantly changes their password.

**Comment by rfk** [comment]
That sounds reasonable.  I think the main purpose of the rate-limiting here is to protect *unauthenticated* email-sending endpoints, which can be an opportunity to spam other users rather than just spam yourself.  @vbudhram feel free to close this out if you're comfortable that no action needs to be taken here.
