### ISSUE TITLE
Reduce potential for accidental config clobberage in ./scripts/config-set.js

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-customs-server#127]
Noting this while I think of it, based on https://bugzilla.mozilla.org/show_bug.cgi?id=1292424#c2; next action is almost certainly on me to come back with a proper description for the bug...

**Comment by vladikoff** [comment]
from mtg:

* change one value should be easy
* currently it changes a bunch of values

**Comment by rfk** [comment]
Right.  Currently if we do something like:

```
$> echo '{ "requestChecks": { "SecretRequestCheckSettingHere": false } }' | node ./scripts/config-set.js localhost:11211
```

Then any other settings in the "requestChecks" object in memcached will be overwritten.  Once fix could be to have the script read the existing object and merge it with the provided value, rather than just overwriting it wholesale.

**Comment by vladikoff** [comment]
@rfk should we still keep this `next`?

**Comment by rfk** [comment]
Nope.  Let me fix that by moving it into `review` 😁
