### ISSUE TITLE
A modest proposal for a major refactor

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-customs-server#128]
I've been spending a lot of background cycles thinking about the structure of code in this repo, and talking though some parts of it with @seanmonstar.  I think the way it's currently structured is hurting us in a variety of ways:
- Many of the rules implemented here are ad-hoc, and it's not always obvious how particular config values map to particular concrete effects.  See, for example, the recent change w.r.t. blocking email-sending actions at the IP level.
- We want to hide certain implementation details of our rules, e.g. various well-formedness checks that we apply to login requests.  That currently means deploying from a private fork of this repo, because those checks have to be rendered in code.
- It's hard to emit detailed metrics about what's being blocked and why; I've seen two aborted attempts at https://github.com/mozilla/fxa-customs-server/issues/106 because it would involve major surgery to the structure of the code.

Given that we now have significant operational experience with this repo, it's time to consider refactoring it to make the rules it offers easier to understand, easier to change and configure, and easier to monitor in production.

So, a proposal based around a small set of unifying concepts:
- The whole job of this server is to check an incoming **request** and make recommendations on what to do with it.  The data we have about the request includes the source ip address, the target email or uid, the target action, the headers, body payload, etc.  We basically have this structure right now, although it could be made more explicit in the code.
- We check said **request** by applying a list of **rules**.  Each rule has a name and can be independently configured.  Each rule is an instance of one of a small number of concrete _types_ of rule, such as "rate limit" or "check request structure", for which we provide implementations in the public repo.  But the precise details of each instantiation of a rule come from private config.
- Whenever a rule is matched, we can apply one or more **sanctions** to the request.  We might recommend it be blocked, or rate-limited, or treated with suspicion.  We might add the IP or the email to an internal blocklist.  We have a small set of these available and they're orthogonal to the list of rules.

Having an explicit list of rules with meaningful names, will let us log much better metrics about which of them are triggering and against what requests.  It will also make it easier to understand exactly what the rules _are_ at any point in time.  And having them be instantiated from config will mean we can keep various details private just by putting them in the puppet-config repo and/or directly in memcached.

What might it look like in practice?  Here's a strawman config that could replace some of the current hard-coded rules with something more declarative.  (Don't get too caught up in the details, I'm just trying to get the idea out of my head).

```
{
  // Some global config that's the same as we have right now
  "allowedIps": ["63.245.214.162", "63.245.214.168" ],
  "allowedEmaiLDomains": ["restmail.net"],

  "rules": {

      // An instance of the rate-limiting rule, which
      // limits any one email address to 3 login attempts in 15 minutes.
      // If you go over that limit, we block the request.

      "limit_logins_by_email": {
         "type": "RateLimit",
         "match": {
             "action": "accountLogin",
         },
         "config": {
           "groupBy": "email",
           "limit": 3,
           "period": "15 minutes",
         },
         "sanctions": {
             block: true
         }
      },

      // An instance of the rate-limit-unique-attempts rule, which
      // limits an IP address from logging in to more than 3 unique
      // accounts in half an hour. If you go over that limit, not only
      // do we block the request, but we ban your IP for 6 hours.

      "limit_unique_logins_by_ip": {
         "type": "RateLimitUnique",
         "match": {
             "action": "accountLogin",
         },
         "config": {
           "groupBy": "ip",
           "uniqueBy": "email",
           "limit": 3,
           "period": "30 minutes",
         },
         "sanctions": {
             block: true,
             banIp: "6 hours"
         }
      },

      // We can also just limit total requests
      // by any particular IP address.

      "limit_requests_by_ip": {
         "type": "RateLimit",
         "config": {
           "groupBy": "ip",
           "limit": 200,
           "period": "1 hour",
         },
         "sanctions": {
             block: true
         }
      },

      // An instance of a structural checking rule, which
      // tells us to be more suspicious of requests that don't
      // have the X-Requested-With header that we'd expect
      // for requests coming from content-server.

      "check_xhr_header": {
         "type": "CheckStructure",
         "config": {
           // there must be an existing query language for this, right?
           "expr": "headers.x-requested-with != 'XmlHttpRequest'"
         },
         "sanctions": {
             suspect: true
         }
      }

      // An instance of a blocklist checking rule, which
      // blocks requests from anything on the firehol level 1 list.

      "firehol_level1": {
         "type": "IPBlocklist",
         "config": {
           "file": "/path/to/wherever/the/file/is/stored.txt",
           "refreshInterval": "5 minutes"
         },
         "sanctions": {
             block: true
         }
      }
}
```

In pseudo-code, the core algorithm of the server would them look like the following:

```
    function checkRequest(request) {

       // Some rules are stateful, they need a place to store it.
        var ip_record = loadIpRecord(request.ip)
        var email_record = loadIpRecord(request.email)

        // Check each rule in turn.
        var sanctions = {}
        config.rules.forEach(function(rule) {
            if (rule.appliesTo(request)) {
                if (rule.check(request, ip_record, email_record)) {
                   // You failed a rule, sad trombone.
                   merge(sanctions, rule.sanctions)
                   // Also, we can log really detailed info about what triggered and why.
                   log.info("rule triggered", {
                       rule: rule.name,
                       request: request
                   })
                }
            }
        })

        // Save any modified state.
        saveIpRecord(request.ip, ip_record)
        saveEmailRecord(request.email, email_record)

        return sanctions
    }
```

I'm sure there are parts of what the server currently does that wouldn't fit this model.  For example, the above doesn't distinguish between successful or failed login attempts.  But I feel like the server as a whole would be easier to work with and reason about if we refactored it towards a model like the above.

Anyways, just an idea at this stage, putting it out there for discussion.  @seanmonstar @vbudhram @vladikoff @larissagaulia as the folks who've worked with this repo most recently, thoughts?

**Comment by seanmonstar** [comment]
I love it. Seeing all the rules as a list would be far easier to understand what is happening, as well as adding a new one in the thick of things.

We've started adding customs support to other servers, we may start needing a way to specify "these rules apply to this server, but not any other".

**Comment by vladikoff** [comment]
Let's reopen once we get back to customs-server in the future
