### ISSUE TITLE
Automatic updating of IP list sets

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-customs-server#130]
This is an issue to help track the progress of getting IP blocklist to update automatically. From meeting with Ops team, decided to move the updating process out of the webheads and into an admin box. Another script (puppet?) will be responbile for updating the customs server files.

Notes: https://docs.google.com/document/d/16XWpLgyxZKsAg0YxhqTprKpcyjlaMwXvFMLOqg3WC-c/

Ref PR: https://github.com/mozilla/fxa-customs-server/pull/117
Ref feature: https://github.com/mozilla/fxa-features/issues/6

**Comment by vbudhram** [comment]
cc @jbuck @jrgm

**Comment by vladikoff** [comment]
@vbudhram has more up to date details on this ....

**Comment by vbudhram** [comment]
From last review puppet config needs to update fxa-admin box to pull in latest blocklist.

**Comment by vladikoff** [comment]
from mtg: needs update to pull files from S3...

**Comment by vbudhram** [comment]
Closed via https://github.com/mozilla-services/puppet-config/pull/2410
