### ISSUE TITLE
Integrating with tigerblood

### ISSUE THREAD

**Issue by autrilla** [mozilla/fxa-customs-server#134]
Tigerblood is mozilla-services' new centralized IP-reputation system. Considering fxa-customs-server already has its own metrics to determine whether an IP is untrustworthy, it'd be useful if it could tell tigerblood whenever it blacklists an IP. In contrast to fxa's binary blocked/allowed, tigerblood assigns a value from 0 (fully untrusted) to 100 (fully trusted) to a given IP. Tigerblood exposes a simple HTTP API, which you can see [here](https://github.com/mozilla-services/tigerblood/tree/api-docs#http-api). With tigerblood, an IP's reputation increases over time, so in practical terms this is similar to the memcached ttl you set, so the higher the ttl you set, the more the reputation for that IP should be reduced.

Is this something you'd be willing to do?

Please let me know if you have any questions about tigerblood or the integration, either here or on IRC (:autrilla)

cc @jvehent

**Comment by rfk** [comment]
> Is this something you'd be willing to do?

Broadly, yes, this is definitely something we'd be happy to do.  We'll need to figure out how to fit it into our over dev planning/scheduling, so I'm not going to commit to *when*, but we certainly *will* :-)

**Comment by rfk** [comment]
Out of curiosity, what other sources does tigerblood take reputation data from?

**Comment by autrilla** [comment]
Currently, none. There's medium/long-term plans to make it take reputation data from requests done to the service itself. For example, if many services start asking about the same IP very often, it's likely that IP is doing something suspicious.

**Comment by jvehent** [comment]
@rfk I'd like to get someone from our side contribute to customs-server to implement this. It'll be a good learning experience for us, as we want to help other services integrate with the ip reputation service. Could you recommend someone from the FxA team to help us navigate the code?

**Comment by rfk** [comment]
@vbudhram would be a good bet on our side

**Comment by vbudhram** [comment]
@jvehent I can definitely help with this. What is the best would work best for you guys? Should we schedule a meeting?

**Comment by vbudhram** [comment]
@jvehent initial integration was merged in from https://github.com/mozilla/fxa-customs-server/pull/148. Should we close this and file follow on bugs for new issues?

**Comment by vladikoff** [comment]
Integration is a go! as @vbudhram mentioned, @jvehent please file new issues if we need updates to the integration.
