### ISSUE TITLE
`npm test` leaves a turd `test/mocks/temp.netset` file

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-customs-server#139]
If possible, either clean up, or better, use a real temp file.

**Comment by rfk** [comment]
I recently fixed this as part of #137:

  https://github.com/mozilla/fxa-customs-server/pull/137/commits/623de15c807068269ca19ae349350ae116c934ab#diff-cc09e5d5a69125db92d1895f55b0ee14R277

Can you confirm if this fix works for you on latest master?

**Comment by jrgm** [comment]
Yep. On public master, it is cleaned up. Thanks.
