### ISSUE TITLE
fix logging of `msg` member 

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-customs-server#140]
In production logs, I get `"msg":"",`. However, I know that `msg` is not the empty string in the code. I don't know where this is getting lost, but it should be in the logs.

**Comment by rfk** [comment]
After a bit of sleuthing, it appears this repo uses bunyan [1] which applies special semantics to the key "msg" in its logging.  The simplest option is going to be to call our key something else.

[1] https://www.npmjs.com/package/bunyan
