### ISSUE TITLE
Log hashed ip address to ip blocklist hits

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-customs-server#147]
To better help us understand the IP addresses that getting hit on our blocklists, we should log a hashed version of the IP. This will help us resolve the question if it is the same address or different address.

Ref: https://github.com/mozilla/fxa-features/issues/6#issuecomment-261356880

**Comment by jvehent** [comment]
Hashing IPs isn't very useful because the field is limited to 4B possibilities. Even with a salt, it's trivial to reverse. I'd recommend just logging the IP itself.

**Comment by rfk** [comment]
s/hashed/hmaced/ in the same manner we do for metrics exports of e.g. the FxA uid.  But still, I'll defer to your advice if you don't think it's worth it.  For a concrete example of what we want to do, you can image an "ip" field showing up in the records on this dashboard:

  https://kibana-fxa-us-west-2.prod.mozaws.net/index.html#/dashboard/elasticsearch/PROD%20-%20IP%20Blocklist%20Stats

**Comment by jvehent** [comment]
As long as access to the IP data is limited to a group of people and not shared with the entire org, I don't think obfuscating it is a requirement.

**Comment by rfk** [comment]
OK, let's just log it raw in the code then; we can always add obfuscation downstream if we decide we need it when dumping to a particular place for exploration (again, like we do with the uids that go into S3/redshift/redash)

**Comment by vladikoff** [comment]
from mtg:

@vbudhram can you link the Bugzilla bug here?

**Comment by vbudhram** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1330352. The plan is to hash ips when being imported.

**Comment by vbudhram** [comment]
Closing issue since bugzilla bug has been resolved.
