### ISSUE TITLE
intermittent test failures in retryAfter 

### ISSUE THREAD

**Issue by g-k** [mozilla/fxa-customs-server#158]
refs: https://github.com/mozilla/fxa-customs-server/issues/153 https://github.com/mozilla/fxa-customs-server/pull/152#pullrequestreview-16365892

[This branch](https://github.com/mozilla/fxa-customs-server/compare/master...g-k:flaky-email-record-test?expand=1) adds a test case that fails intermittently (for me at least).  In bash or zsh it can be run until failure (usually within ten seconds) with: `while node_modules/.bin/tap test/local/flaky_email_record_test.js; do :; done`

The test fails on v0.78.0 so the issue isn't limited to changes in https://github.com/mozilla/fxa-customs-server/pull/152.

Should apply to all rate limit tests hitting the `/check` route where `limits.rateLimitIntervalMs` is 1000 and now is `Date.now`, but I've only looked at `too_many_verify_codes`.

The failures seem to stem from computing `Math.floor(0.999)` when calculating [rateLimitAfter](https://github.com/mozilla/fxa-customs-server/blob/master/lib/email_record.js#L136).

Possible fixes:

* don't worry about it and rerun tests
* include a tolerance param in the comparision
* run flaky tests with acceptance criteria like 2/3 runs pass, so adding new rate limit tests don't increase the overall failure rate

#### Background

Working on https://github.com/mozilla/fxa-customs-server/pull/152, it was weird that  [too_many_verify_codes](https://travis-ci.org/mozilla/fxa-customs-server/jobs/191366059) and [too_many_account_status_check](https://travis-ci.org/mozilla/fxa-customs-server/jobs/191363227) failed in addition to tests I added (especially after [wiping memcache](https://github.com/mozilla/fxa-customs-server/commit/4f5d781e6dceb765ab96b8c8b305bb7023a55536#diff-29937e99d30174d1de102c03acaa8a22)).

The fix for https://github.com/mozilla/fxa-customs-server/issues/153 reduced the error rate for the send violations tests, but it still failed occasionally.

**Comment by g-k** [comment]
Anyway, curious if anyone else sees a failure running the test case in that branch.

**Comment by rfk** [comment]
I can confirm I've seen weird failures in the `too_many_verify_codes` test, that match what you're describing here.

> The failures seem to stem from computing Math.floor(0.999) when calculating rateLimitAfter.

And this is right on the money.  If the update logic calls `this.rateLimit()` at time `t` milliseconds, and calls `this.retryAfter()` at time `t+1` milliseconds, then the calculation in `retryAfter` will return zero.

I wonder if we could just switch to `Math.ceil` here instead of `Math.floor`, so we round your ban time *up* to the nearest second rather than rounding it down.
