### ISSUE TITLE
Blanket errors when using arrow functions

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-customs-server#164]
When using the current version of `ass` coverage lib, blanket errors out on arrow functions.

```
                            throw new Error("BLANKET-Error parsing instrumented code: "+err);
                            ^

Error: BLANKET-Error parsing instrumented code: Error: Line 66: Unexpected token >
    at /Desktop/working/fxa-customs-server/node_modules/ass/node_modules/blanket/src/index.js:167:35
```

**Comment by vladikoff** [comment]
Yea we need to switch the coverage tool, just like the rest of the servers

**Comment by shane-tomlinson** [comment]
Ah yes.. That's one of the reasons we have to convert using Babel when running the coverage tool on the content server.

**Comment by vladikoff** [comment]
Example: https://github.com/mozilla/fxa-auth-server/blob/38d4957f2816f6aa546cb144dfdc58185a6740ca/scripts/test-local.sh#L13
