### ISSUE TITLE
Oddity with PR 151; handling of JSON array merging

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-customs-server#168]
Start with local memcache with no data (command `flush_all`). Then do this
```
File ary.json:

{
  "allowedIPs": [ 
    "55.55.55.55"
  ]
}

$ ./scripts/config-list.js 127.0.0.1:11211; \
    cat /tmp/ary.json | ./scripts/config-set.js 127.0.0.1:11211; \
    echo @@@@@; ./scripts/config-list.js 127.0.0.1:11211
no limits set
no allowedIPs set
no allowedEmailDomains set
no requestChecks set
{
  "limits": {},
  "allowedIPs": [],
  "allowedEmailDomains": [],
  "requestChecks": {}
}
@@@@@
no limits set
no allowedEmailDomains set
no requestChecks set
{
  "limits": {},
  "allowedIPs": {
    "0": "55.55.55.55"
  },
  "allowedEmailDomains": [],
  "requestChecks": {}
}
```

So `allowedIPs` comes back as a hash with numeric keys. This was not the previous behaviour. (And yeah, an Array is an Object with numeric keys and a .length, but....).

**Comment by rfk** [comment]
Bleh, I guess this is doing the equivlent of `lodash.merge({}, ["55.55.55.55"])` and winding up with an object instead of an array :-(

**Comment by rfk** [comment]
@jrgm for `allowedIPs` and `allowedEmailDomains`, does it make sense to just overwrite with the provided value rather than try to merge the input array with any existing array?  ISTM that would be simpler and preferable overall, and would have the happy effect of making this bug easier to fix.

**Comment by jrgm** [comment]
Yeah, maybe clobber for Array members, and merge for Object members.  And warn when clobbering will happen. Otherwise there is now way to remove elements from Array.
