### ISSUE TITLE
Waiting time after throttling (5 messages) is 30 minutes, not 60 minutes as per specifications

### ISSUE THREAD

**Issue by kkumari22** [mozilla/fxa-customs-server#185]
Prerequisite: Existing SessionToken
STR:
1. Navigate to 'https://accounts.firefox.com/sms?service=sync'
2. Enter phone number in mobile number field and click send to send SMS
3. Repeat step 1 and 2 to send more than 5 messages to valid phone number within the span of an hour
 
Expected: User gets throttled after 5 messages and have to wait for 60 minutes to send additional messages.

Actual: Waiting time after throttling (5 messages) is 30 minutes, not 60 minutes. See below in image, it was captured on the 6th try right after sending the 5th SMS:
![morethanfivesms](https://cloud.githubusercontent.com/assets/16670573/23809918/4a5465d4-0584-11e7-8e52-cf40bf61123b.PNG)

**Comment by kkumari22** [comment]
Today waiting time after throttling (5 messages) is 15 minutes. See below in image, it was captured on the 6th try right after sending the 5th SMS:
![sms](https://cloud.githubusercontent.com/assets/16670573/24126300/6eaa2032-0d8a-11e7-9b30-a1b5daea6b39.PNG)

**Comment by rfk** [comment]
To clarify, is this sending to the same number five times, or sending to five different numbers from the same IP address?

**Comment by rfk** [comment]
(The block time for the later, is based on `IP_RATE_LIMIT_BAN_DURATION_SECONDS` config and I think is currently less than 60 minutes).

**Comment by rfk** [comment]
The linked PR #189 fixes this for the "same number five times" case, but not for the other case.

**Comment by kkumari22** [comment]
1. This is to confirm that the original issue was opened for 5 different phone numbers from the same office wifi/IP Address. In this case, I observed 30 minutes of waiting time as opposed to 60 minutes (per the specifications).

2.  Today's observation of 15 minutes waiting time was for using the same phone numbers more than 5 times from the same office wifi/IP Address.

3. Yes, I looked into the config changes specified in #189 and it seem that it would fix #2 scenario but not #1 scenario,

**Comment by rfk** [comment]
> This is to confirm that the original issue was opened for 5 different phone numbers
> from the same office wifi/IP Address. In this case, I observed 30 minutes of waiting
> time as opposed to 60 minutes (per the specifications

/cc @shane-tomlinson for input, but I want to propose that we adjust the specification here to bring the wait time down to 30 minutes for this scenario, to make it consistent with other ip-level blocks that we already have in place.

**Comment by shane-tomlinson** [comment]
Resolution is to update the docs with the current config times, 30 mins per IP, 60 mins per phone number. We'll re-visit once we see how this acts in prod.

**Comment by vladikoff** [comment]
need to update the docs...

**Comment by shane-tomlinson** [comment]
@kkumari22 - I am trying to find a reference to rate limiting in [the feature spec](https://github.com/mozilla/fxa/tree/master/features/FxA-53-send-sms) but am coming up blank. Do you have a source available? I'd like to update the spec to match reality.

**Comment by kkumari22** [comment]
It's in the feature spec under [submitting a valid phone number](https://github.com/mozilla/fxa/tree/master/features/FxA-53-send-sms#submitting-a-valid-phone-number) section.

**Comment by shane-tomlinson** [comment]
@kkumari22 - thank you for the link!
