### ISSUE TITLE
'Download on the App Store' and 'Get it on Google Play' links/icons are missing on iOS and Android devices

### ISSUE THREAD

**Issue by kkumari22** [mozilla/fxa-customs-server#187]
Prerequisite: Existing SessionToken
STR:
1.Navigate to 'https://accounts.firefox.com/sms?service=sync'
Note: Tested on iPhone, IPad, Android mobile/tablet

Expected: There should be 'Download on the App Store' and 'Get it on Google Play' link

Actual: 'Download on the App Store' and 'Get it on Google Play' links/icons are missing on iOS and Android devices

![smspage](https://cloud.githubusercontent.com/assets/16670573/24012622/dadd22f6-0a3b-11e7-9676-9d778efc4e5d.png)
![smssentpage](https://cloud.githubusercontent.com/assets/16670573/24012628/e1e27aa6-0a3b-11e7-8613-3f65c35f8124.jpg)

**Comment by rfk** [comment]
Migrated to content-server repo as https://github.com/mozilla/fxa-content-server/issues/4817; thanks @kkumari22!
