### ISSUE TITLE
SMS throttled limit is not honored for a specific FxA account if different machines are used for sending SMSs

### ISSUE THREAD

**Issue by kkumari22** [mozilla/fxa-customs-server#188]
Prerequisite:
1. Existing SessionToken
2. Availability of multiple machines

STR:
1. On a specific machine, navigate to 'https://accounts.firefox.com/sms?service=sync'
2. Enter phone number in mobile number field and click send to send SMS.
3. Repeat step 1 and 2 for 4 times to send 4 messages to valid phone numbers within quick span (less than an hour).
4. Using the same FxA account repeat step 1, 2, & 3 on multiple machines (same office wifi/IP Address) .

Expected: SMS throttled limit of 5 messages should be honored for a specific FxA account even if different machines (same office wifi/IP Address) are used for sending SMSs.

Actual: SMS throttled limit is not honored for a specific FxA account if different machines (same office wifi/IP Address) are used for sending SMSs.

For e.g. It is very much possible to send up to 40 SMSs from the same FxA account if the user tries from 10 different systems.

**Comment by rfk** [comment]
> Repeat step 1 and 2 for 4 times to send 4 messages to valid phone numbers within quick span (less than an hour).

Just to be clear, using *different* phone numbers of each attempt?

**Comment by kkumari22** [comment]
Yes I used 4 different phone numbers on each attempt. e.g. On machine 1, sms to 4 different numbers and then on machine 2, I could send sms to > 2 (different numbers from machine 1) phone numbers for same Fx account within an hour.

**Comment by vladikoff** [comment]
cc @vbudhram
