### ISSUE TITLE
adjust the Limits pushOnEmpty to not consume unrelated errors

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-customs-server#194]

**Comment by jrgm** [comment]
Note: from surrounding log messages, `limit.push` happened due to this condition https://github.com/mozilla/fxa-customs-server-private/blob/master/lib/allowed_ips.js#L55-L58, which 14 of 15 hosts did not see, but one did (which is wut?).

**Comment by jrgm** [comment]
Hmm. So the ec2 that did the `limit.push` was the first ec2 of the 15 to begin running...

**Comment by vladikoff** [comment]
from mtg: customs server memcache connection had issues with this. @seanmonstar did you have a plan for this ?

**Comment by vladikoff** [comment]
from mtg: @jrgm says this is a serious issue, needs `next`
