### ISSUE TITLE
Add rate-limiting for signinCodes

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-customs-server#201]
Related: mozilla/fxa-auth-server#1882

**Comment by philbooth** [comment]
Clarification: this is rate-limiting for the endpoint that consumes signinCodes. Rate-limiting for sending SMS messages already exists.

**Comment by philbooth** [comment]
Not sure if these had already occurred to anyone else, but I've only just started to think them through:

1. The customs server is heavily geared towards having an email address (or a uid) to rate limit against. Obviously here we have neither of those, nor anything that can stand in for them, so we're rate-limiting by IP address only.

   Getting any kind of re-use from the existing code in that case, it turns out, requires quite a lot of refactoring that unravels quite quickly. I don't want to mess with the existing customs checks to that extent, so am opting for a dedicated `/checkIpOnly` endpoint that mostly does its own thing.

2. Looking at the actions in `lib/actions`, for this phase signinCodes seem to have most in common with the `CODE_VERIFYING_ACTION` group.

   But in the next phase, it seems like they have more in common with `PASSWORD_CHECKING_ACTION` group. Or perhaps they even warrant a slightly different `ACCOUNT_ACCESS_ACTION` (or whatever) group. Should we start off with them in whatever their ultimate action group will be right away, or should we cross that bridge when we come to it?

   Usually, I'd be firmly in the latter camp, but I'm not sure what the implications of changing groups later might be, with regards to stuff that's stored in memcached. Perhaps there are no implications but I don't understand the code well enough at the moment to be certain.

**Comment by philbooth** [comment]
> ...signinCodes seem to have most in common with the `CODE_VERIFYING_ACTION` group.

And I just notice that group is another thing heavily intertwined with the presence of an email address. `IpRecord.addVerifyCode` assumes an `email` property, so it really seems like signinCodes are a different type of action.

**Comment by philbooth** [comment]
> Getting any kind of re-use from the existing code in that case, it turns out, requires quite a lot of refactoring that unravels quite quickly.

Actually, I think I over-estimated the unravelling here. After sticking with it for a bit, the refactoring hasn't turned out too bad. I'm still using a dedicated `/checkIpOnly` endpoint, but it's able to re-use a lot of the code we have elsewhere.

**Comment by rfk** [comment]
> so it really seems like signinCodes are a different type of action to me.

FWIW this sounds fine to me
