### ISSUE TITLE
Current implementation of allowWhitelisted causes problems for /checkIpOnly

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-customs-server#205]
When running the content server functional tests, lots of requests to `/check` originate from the same IP address. These cause the rate limit flag to be set in `IpRecord`, but the request itself is not blocked because the email address matches the test in `allowWhitelisted`.

This is all fine until requests to `/checkIpOnly` start turning up. Now, the `IpRecord` is still marked as rate-limited when it is fetched from memcached, but we have no email address to whitelist on. So those requests get blocked, even though the specific action they're checking is below its threshold.

It seems like the correct behaviour is for `allowWhitelisted` to clear any flags on the `IpRecord` whenever there's a match.

**Comment by rfk** [comment]
> It seems like the correct behaviour is for allowWhitelisted to clear any flags on the IpRecord
> whenever there's a match.

An alternative would be to somehow count `ACCOUNT_ACCESS_ACTION` actions in a separate bucket, rather than applying the ip-wide rate-limiting rule.  In practice this might look like changing the code here:

  https://github.com/mozilla/fxa-customs-server/blob/master/lib/ip_record.js#L257

So that it short-circuits the generic "was this IP rate-limited?" check.  It might look something like this:

```
    if (actions.isAccountAccessAction(action)) {
      this.addAccountAccess()
      if (this.isOverAccountAccessLimit()) {
        // The IP is behaving badly, rate-limit it for all actions, and reject this attempt.
        this.rateLimit()
        return this.retryAfter()
      }
      // But, account-access actions are relatively safe,
      // so we can still allow them even if the IP is rate-limited due to other actions.
      return 0
    }
```

That's a hack, but it has the advantage of only affecting this one type of action.  Thoughts?  Would this increase our risk profile significantly in practice?

**Comment by philbooth** [comment]
> An alternative would be to somehow count `ACCOUNT_ACCESS_ACTION` actions in a separate bucket, rather than applying the ip-wide rate-limiting rule.

Funnily enough, returning `0` was actually my first attempt at fixing this. It works but I was concerned that discarding information from the `rl` and `bk` flags like that would let bad actors through in the wild. If someone has been legitimaely blocked or rate-limited, we definitely want to honour that don't we?

**Comment by philbooth** [comment]
There is another fix to all of this, which is just to make sure the config for the dev boxes has thresholds that are high enough across the board. We can leave the customs code completely untouched then. Maybe that's better than trying to jump through hoops in production code, for the benefit of the tests?

/cc @shane-tomlinson, not sure what you think on this point?
