### ISSUE TITLE
Prefer sets to arrays for IP address lists?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-customs-server#219]
Checking for existence in a set is quicker than iterating through an array.

**Comment by vladikoff** [comment]
@philbooth do you mean these https://github.com/mozilla/fxa-customs-server/blob/master/lib/ip_blocklist.js#L50 ?

**Comment by philbooth** [comment]
Not 100% sure which arrays I mean tbh, because I don't properly understand the code in this repo. But whichever arrays might be a good candidate for sets, I mean those. (e.g. the ones in IpRecord?)

**Comment by vbudhram** [comment]
from mtg: not doing anytime soon
