### ISSUE TITLE
Start memcached if not running as part of `npm test`

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-customs-server#228]
Ref: https://github.com/mozilla/fxa-customs-server/pull/227#issuecomment-363468963

**Comment by g-k** [comment]
Exiting and telling the dev to make sure memcached is running would work too.

**Comment by vladikoff** [comment]
> Exiting and telling the dev to make sure memcached is running would work too.

Good backup solution :)

**Comment by vladikoff** [comment]
cc @deeptibaghel 

This is very close to https://github.com/mozilla/fxa-local-dev/pull/100

If you run `npm test` without memcached right now a lot of tests will fail. 
Once we land a fix in https://github.com/mozilla/fxa-local-dev/pull/100 then it will be okay, but some devs do not use fxa-local-dev, so we need to add logic to start memcached into this project.

**Comment by deeptibaghel** [comment]
@vladikoff I would like to work on this.

**Comment by vladikoff** [comment]
@deeptibaghel sounds good, see this file https://github.com/mozilla/fxa-customs-server/blob/master/test/memcache-helper.js I Think if you make a fix in there, it should run the `spawn` command and run memcached server (if it is not running already) when that file is required.

**Comment by vladikoff** [comment]
@deeptibaghel from the looks of it you might be better off using https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options  (synchronous call to start the server)

and run that before this line https://github.com/mozilla/fxa-customs-server/blob/master/test/memcache-helper.js#L40
