### ISSUE TITLE
Add custom rate limit rule for consuming recovery codes

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-customs-server#238]
Continuing from https://github.com/mozilla/fxa-auth-db-mysql/pull/333#discussion_r182566328, we should expose a rate limit rule specifically for recovery codes.

Since each user only has 8 recovery codes at a time, I can see a reasonable limit as 8 attempts per 15 mins per email.

**Comment by jrgm** [comment]
If implemented, update docs here: https://github.com/mozilla/fxa-customs-server/blob/master/README.md#policies

**Comment by rfk** [comment]
Fixed by https://github.com/mozilla/fxa-customs-server-private/pull/46
