### ISSUE TITLE
Complete Tigerblood integration

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-customs-server#245]
Opening this because I haven't been able to find an issue on it anywhere else and don't want to lose track of it.

@g-k is working on the Tigerblood and would like to integrate with FxA sometime soon. This is an issue to keep track of remaining work from the FxA side.

**Comment by g-k** [comment]
👍 

cc @ameihm0912 who's driving things on the secops side

**Comment by ameihm0912** [comment]
@shane-tomlinson this was completed and I believe can be closed off

**Comment by shane-tomlinson** [comment]
Thanks @ameihm0912! Closing.
