### ISSUE TITLE
Prepare a v1.118.1 release of customs to pick up fixes for keepAliveTimeout

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-customs-server#268]
@shane-tomlinson - I don't know what the proper recipe is to produce a v1.118.1-private tag on the private repo, so can you do that and I can ship that tomorrow. This is to pick up the two fixes for keepAliveTimeout in HEAD of origin/master of fxa-customs-server. Thanks.

**Comment by shane-tomlinson** [comment]
@jrgm - customs-server-private tag v1.118.1-private created! Bugzilla bug updated. Closing.
