### ISSUE TITLE
seeing production timeouts on auth requests to customs server

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-customs-server#275]
Throws a Function.AppError.backendServiceFailure. In auth logs, before that is `{"op":"customs.check.1","email":"someone@example.com","action":"accountLogin",
"err":"EndpointError: 127.0.0.1:7000 error: request timed out"}}`. I don't see anything interesting in the customs log at about the same time (except maybe a lack of activity at that time, but that's anecdotal information since I've only correlated a few cases).

**Comment by rfk** [comment]
from mtg: maybe the timeout config is too low (1 sec?)

**Comment by rfk** [comment]
We could also add more info to this log message, e.g. request start time.

**Comment by vladikoff** [comment]
Need to adjust the timeouts such that the iprepd timeout is shorter than then customs request timeout in the auth server
