### ISSUE TITLE
Stackdriver Logging schema error

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa-customs-server#319]
This is a follow-up to #314. The error is `Field jsonpayload.future: Cannot convert bool value to floating point:0` . Here's the message that has the error:

```
{
  current:  true   
  future:  false   
  hostname:  "ip-172-31-56-89.ec2.internal"   
  key:  "flowIdRequiredOnLogin"   
  level:  30   
  msg:  ""   
  name:  "customs-server"   
  op:  "requestChecks.validate.changed"   
  pid:  1   
  v:  0   
 }
```

@philbooth I guess that https://github.com/mozilla/fxa-customs-server/blob/6376028ecb95c45933a0abe73e887fbfedd4bd52/lib/settings/requestChecks.js#L43 needs to be changed similar to https://github.com/mozilla/fxa-customs-server/pull/315/commits/469ca49eab6789aad70595483169ae52c498a464#diff-62731ee8b1c74763166204909a5d21e0R61 ?

**Comment by philbooth** [comment]
Looks like it, yeah. On it!
