### ISSUE TITLE
Check API requests for the OAuth server

### ISSUE THREAD

**Issue by fmarier** [mozilla/fxa-customs-server#33]
As a first step towards detection and mitigation of abuse in the OAuth server APIs, the customs server should be added in that codebase without rejecting any of the requests.

The OAuth server has three APIs:

1. browser -> oauth server: (assertion, clientID, scopes, redirectURI) -> code [[/authorization](https://github.com/mozilla/fxa-oauth-server/blob/master/lib/routes/authorization.js)]
2. RP -> oauth server: (code, appID, appSecret) -> token [[/token](https://github.com/mozilla/fxa-oauth-server/blob/master/lib/routes/token.js)]
3. service provider (e.g. Profile Server) -> oauth server: (token, scope, fxaUUID) -> valid? (true/false) [[/verify](https://github.com/mozilla/fxa-oauth-server/blob/master/lib/routes/verify.js)]

**Comment by rfk** [comment]
From triage, we're going to depend on generic infra-level abuse mitigation rather than try to do anything custom with oauth-server.  Unlike some other endpoints, there's nothing here that could be brute-forced so we don't need special-case protection logic.
