### ISSUE TITLE
Keep track of emails sent over the throttling limit

### ISSUE THREAD

**Issue by fmarier** [mozilla/fxa-customs-server#69]
The current graphs we have to detect "fraud" related to too many password attempts (graphing the number of "block: true" coming from the customs server when maxEmails is reached) are not so useful because things like graylisting will cause normal people to click lots of times on the "resend code" button.

This throttling is useful because sending more than 10 emails is not going to help if the first one takes too long to arrive so we may as well limit the outgoing emails we send. Once a user is throttled, we no longer keep track of how many emails they attempt to trigger.

Maybe we should continue to count the emails and alert when that count is very high (e.g. 100 emails in a 15 minute period). This is something that we should normally not see and that would indicate that something bad might be happening.

**Comment by rfk** [comment]
I can't see us prioritizing this, closing it out
